name: Generate PDF documentation

on:
  workflow_dispatch: {}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup Python
      uses: actions/setup-python@v4.5.0
      with:
        python-version: '3.x'
    - name: Install and build dependencies
      run: ./setup.sh --doc
    - name: Generate documentation
      run: make doc
    - name: Upload generated pdf
      uses: actions/upload-artifact@v3
      with:
        name: ublox_parser_reference
        path: doc/latex/refman.pdf
        retention-days: 5
