name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4.5.0
      with:
        python-version: '3.x'
    - name: Install and build dependencies
      run: ./setup.sh
    - name: Build
      run: make build
    - name: Test
      run: make test
